### ISSUE TITLE
疑问🤔: 假设服务异常退出，中断，任务的流转是否会受到影响

### ISSUE THREAD

**Issue by hanshuaikang** [Bunny3th/easy-workflow#1]
看到大多数节点是审批节点，服务异常退出，审批节点如果有人审批，还是可以驱动流程正常向下流转的，如果加入自动节点类型，节点执行完自动流转到下一个节点的话，此时如果服务突然中断，现有的设计下任务会不会被中断。

**Comment by Bunny3th** [comment]
不会的。因为任务的状态都是记在数据库中，而数据库是有事务性的，要么任务通过，要么任务驳回。所以不用担心。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月7日(周五) 下午5:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Bunny3th/easy-workflow] 疑问🤔: 假设服务异常退出，中断，任务的流转是否会受到影响 (Issue #1)




 
看到大多数节点是审批节点，服务异常退出，审批节点如果有人审批，还是可以驱动流程正常向下流转的，如果加入自动节点类型，节点执行完自动流转到下一个节点的话，此时如果服务突然中断，现有的设计下任务会不会被中断。

**Comment by hanshuaikang** [comment]
假设我现在的流程没有审批节点：A - B - C - D 4 个分别是 api 节点，作用是A调用完api之后执行B，以此类推，在服务没挂的时候，可以从自动 从 A 流转到 D节点，假设 B - C 节点中服务挂了，此时即使重启服务，B 也不会自动走到D节点了。

**Comment by Bunny3th** [comment]
&nbsp; &nbsp; &nbsp; &nbsp; 我不知道您指的api节点是什么。猜一下：是不是您使用节点中的开始事件，实现调用特定api，而后在api调用成功后结束此节点，进入下一个节点？
&nbsp; &nbsp; &nbsp; &nbsp;节点开始事件只能在进入节点的时候执行一次，所以确实会存在这样的情况：在开始事件调用api失败的情况下，由于开始事件已经“执行完成”，所以无法重新调用服务。而恰巧您代码逻辑中要求“服务只有调用成功的情况下才能进入下一个节点”。那么这个时候，确实会出现这样的情况。
&nbsp; &nbsp; &nbsp; &nbsp; 如果是以上这样的情况，是否可以在事件代码中加入重试逻辑？这样事件可以保持在“执行等待”状态，等您的api恢复后即可调用成功。
&nbsp; &nbsp; &nbsp; &nbsp;如果我的猜测不对的话，您可以加我的微信，以便做更有效率的沟通。（微信号在说明文档中）



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月7日(周五) 下午5:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Bunny3th/easy-workflow] 疑问🤔: 假设服务异常退出，中断，任务的流转是否会受到影响 (Issue #1)




 
假设我现在的流程没有审批节点：A - B - C - D 4 个分别是 api 节点，作用是A调用完api之后执行B，以此类推，在服务没挂的时候，可以从自动 从 A 流转到 D节点，假设 B - C 节点中服务挂了，此时即使重启服务，B 也不会自动走到D节点了。
