### ISSUE TITLE
建议支持到MYSQL5.7

### ISSUE THREAD

**Issue by jianjianxu** [Bunny3th/easy-workflow#3]
5.7更加的经济适用

**Comment by Bunny3th** [comment]
非常抱歉，目前SQL语句中采用了大量公共表达式（CTE）写法，而5.7并不支持CTE。

**Comment by Bunny3th** [comment]
非常抱歉，目前SQL语句中采用了大量公共表达式（CTE）写法，而5.7并不支持CTE。
