### ISSUE TITLE
 有前端的代码吗？

### ISSUE THREAD

**Issue by TomYang1024** [Bunny3th/easy-workflow#5]
如题

**Comment by Bunny3th** [comment]
没有哦。写完引擎后作者我就陷入了无尽的外包事业中，外包不允许思考。

**Comment by orangle** [comment]
保重身体

**Comment by Bunny3th** [comment]
@orangle  谢谢，已准备转行了。

**Comment by TomYang1024** [comment]
你设计的流程图还是很不错的.
改了改你的代码，准备用到生产上。
还是很感谢你的

**Comment by Bunny3th** [comment]
@TomYang1024 在这一行能留下点念想也算是一个欣慰吧。希望能帮到行内苦逼的同学们吧。
