### ISSUE TITLE
只支持mysql，能否支持其他数据库

### ISSUE THREAD

**Issue by yg7001** [Bunny3th/easy-workflow#7]
能否支持其他数据库？有没有支持其他数据库的计划？

**Comment by Bunny3th** [comment]
综合来看，mysql由于其免费的特性，使用量较多，所以在开发时选择了它。
至于其它类型的数据库，目前没有精力去改。(经济下行，作者年龄40+处于没有公司会要的境地，已经 考虑转行了）
之后这个项目也仅仅会做一些维护。项目完全开源，有能力的同学可以自己尝试修改。
十分抱歉，也十分遗憾。
