### ISSUE TITLE
希望和您进一步交流该项目

### ISSUE THREAD

**Issue by conanwang** [Bunny3th/easy-workflow#8]
您好，最近工作中使用到了工作流的内容，有幸看到您发布的项目，觉得收益很大，很想和您了解下该项目的具体的最佳用法，您是否方便留个联系方式，我的邮箱 26738256@qq.com

**Comment by Bunny3th** [comment]
你好，在项目根目录下《EasyWorkFlow工作流引擎说明文档.pdf》中有我的微信码

**Comment by conanwang** [comment]
感谢您的回复，我加下您的微信
